### PR TITLE
Fix #241

### LINKED ISSUE #241: Error steam.login()
изображение
изображение

Error after in the line :
steam_client.login(username, password, guard)
The error appeared this morning!

Is there a solution?

### PR DESCRIPTION
**Pull request by jiajiaxd**

### CODE REVIEW

**Comment by bukson** [comment]
Is this fixing the login issue?

**Comment by jiajiaxd** [comment]
yep



---Original---
From: ***@***.***&gt;
Date: Mon, Jan 30, 2023 16:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [bukson/steampy] Fix #241 (PR #243)




 
Is this fixing the login issue?

**Review by Juphex — APPROVED** [review]
fix works as intended.
Fixes the login JSON error caused by a wrong url.

**Comment by 4tendev** [comment]
worked for me ty

**Comment by lkurgan55** [comment]
It works, pls merge it

**Comment by MaciejKrempa** [comment]
What to do if it still doens`t work after using this fix? Still problems z json. 
I have changed steampy login.py file with these lines from this fix.

**Comment by CyberKriptor** [comment]
Same with @MaciejKrempa,trying to login but receive "json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

**Review by seeker25 — APPROVED** [review]

**Pull request merged**
