### PR TITLE
start use poetry in project

### PR DESCRIPTION
**Pull request by Derfirm**
[Poetry]( https://poetry.eustace.io) is awesome tool, that help build, publish and track (dependency of course). I suggest starting to use this tool for better and faster development. Let's discuss!

### CODE REVIEW

**Comment by timwoocker** [comment]
I don't see how this helps the project in any way. Can you provide more information on how exactly you want to use it with steampy?

**Comment by Derfirm** [comment]
@timwoocker Nice question!
As for the user - nothing will change, you can use the library as before.
As a developer, the control over dependencies is greatly simplified (BS4, Request and RSA is currently used) without specifying a specific version, which makes it very difficult to understand which version to use. Also, if you experience problems with versions, it is easy to provide a lock file where you can find the problem.
It also simplifies the process of working with semver and releasing a new version (from changing the library version to publishing to pypy).
Work with a virtual environment out of the box, which makes it easier for new developers to create an environment and make their first merge request more faster.

**Comment by bukson** [comment]
Ok, but why don't I just paste thr output of pip freeze command or
somethink like that without introducing more compexity into this project?

niedz., 28 kwi 2019, 15:43 użytkownik Andrew Grinevich <
notifications@github.com> napisał:

**Comment by Derfirm** [comment]
Sounds reasonable, I recommend trying to build / publish and install the environment using poetry. If necessary, I can improve the documentation with a description of how to use it and what pitfalls can be. The advantages are that there is control over the version of the python (now it’s resolved in a setup.py), the ability to simply install the library on the CI from the lock file. Also pip freeze don't guarantee correct packages resolution with extas.

**Pull request closed without merging**
