### PR TITLE
Refresh session + remember login

### PR DESCRIPTION
**Pull request by ThreadShakur**
There i made refresh session func + enable remember_login

### CODE REVIEW

**Comment by ThreadShakur** [comment]
Can some one tests refresh session with trade and etc? Bcs after this refres steam gives false for writing comments

**Comment by grabov** [comment]
What to you think is the better way to use it? I suppose that I have to store time when session was updated last time and update it before request if it is expired (1h for example) Am I right?

**Comment by Zwork101** [comment]
Just whenever it disconnects, have to program call it. Like on a catch our something

**Comment by bukson** [comment]
Ok this method of refreshing session looks fine, but what is that write comment function. Also LoginExecutor.STORE_URL or something instead of writing all domain :)

To sum up, i like first commit, but the second not so much

**Comment by Zwork101** [comment]
Yeah, the I'll change the URL to the enum, but the comment isn't relevant to this pull. There should be another pull, with that method

**Comment by bukson** [comment]
So I will close that till the fix

**Pull request closed without merging**
