### PR TITLE
added texts_between

### PR DESCRIPTION
**Pull request by crey4fun**
This method is a generator for all texts between a start string and an end string.

This is a separate pull request from the receipt one because I don't know how to edit 2 files in one pull request... Sorry

### CODE REVIEW

**Comment by bukson** [comment]
I can't see difference between this method and text_between above, would you like to add tests to utils that shows the difference?

**Comment by crey4fun** [comment]
I think the test I have added shows the usecase pretty well.

**Comment by bukson** [comment]
There is only 1 commit with 1 file changed, i can see no test

**Comment by bukson** [comment]
Merged

**Pull request closed without merging**
