### PR TITLE
Massive refactoring

### PR DESCRIPTION
**Pull request by JustKappaMan**
Hi @bukson 

I **didn't** change any logic and **didn't** use any Python 3.8+ features when refactoring the code.

Approximate change-log:
* Replaced `+`, `%` and `.format()` with f-strings
* Used walrus operator (`:=`) and ternary expression to shorten the code
* Used constants from `http.HTTPStatus` instead of magic numbers (`200`, `429`)
* Replaced `list` with `tuple` where possible (since it's more efficient)
  * `' '.join([...])` -> `' '.join((...))`
  * `for x in [...]:` -> `for x in (...):`
* Made code more pythonic
  * `if len(x) > 0:` -> `if x:`
  * `if x == False:` -> `if not x:`
  * `if x == None:` -> `if x is None:`
  * `if x != '' and y != '' and z != '':` -> `if all((x, y, z)):`
* Used more specific test cases
  * `AssertTrue(x in y)` -> `AssertIn(x, y)`
  * `AssertTrue(x == y)` -> `AssertEqual(x, y)`
  * `AssertTrue(x not in y)` -> `AssertNotIn(x, y)`
  * `AssertTrue(type(x) is str)` -> `AssertIsInstance(x, str)`
* Changed all double quotes to single quotes (since they were already used almost everywhere)
* Formatted the code with [Black](https://github.com/psf/black) using `--line-length 120` and `--skip-string-normalization` flags
* Fixed most of the PEP8 warnings
* Fixed typos and grammar mistakes

Feel free to ask me if there's something wrong with these changes :slightly_smiling_face:

### CODE REVIEW

**Comment by bukson** [comment]
Thank you very much! It is very appreciated. Can you please just squash it to one commit so I have easier time checking it?

**Comment by JustKappaMan** [comment]
@bukson done

**Comment by JustKappaMan** [comment]
@bukson so, what about merging? :smile:

**Comment by bukson** [comment]
Merged manually, thanks!

**Pull request closed without merging**
