### PR TITLE
Abandon pycrypto for better windows support

### PR DESCRIPTION
**Pull request by bukson**
If someone can confim it works i will merge and deploy it.

If none will answer i will test it and deploy it in some time :)

Somebody using windows would be helpfull.

### CODE REVIEW

**Comment by Zwork101** [comment]
After applying the changes, pip was able to install the package. Thanks for taking the time to make it windows compatible. 👍

**Comment by Zwork101** [comment]
If I encounter any errors, I'll tell, you

**Comment by Zwork101** [comment]
Ok, so there was an error.
```python
    from hashlib import shal
ImportError: cannot import name 'shal'
```
Is there a reason why it can't be imported?

**Comment by bukson** [comment]
I can do it on windows using python 3.5.2

**Comment by Zwork101** [comment]
Ok, I'm python 3.6, I'll try it with python 3.5

**Comment by Zwork101** [comment]
Nope, same problem, how can we check what version of hashlib were using?

**Comment by Zwork101** [comment]
XD ok, my bad, my bad, your good, I was typing in shal with an L, not sha1 with a 1, my bad

**Comment by Zwork101** [comment]
Question, where is the steam guard file located?

**Comment by bukson** [comment]
In your phone, there is tutorial there on readme to show how to copy it.

So i will merge it tomorrow if nobody complains by night

**Comment by Zwork101** [comment]
Ok, do I give it the file or the directory string?

**Comment by Zwork101** [comment]
Question, I have two accounts. I've logged onto one of the acccounts on the app, then a different one, and yet there is only one file. How do I get the other account's file?

**Comment by bukson** [comment]
Did you read README? 

steam_client.login('MY_USERNAME', 'MY_PASSWORD', 'PATH_TO_STEAMGUARD_FILE')

**Comment by Zwork101** [comment]
Ok, ignore that last question. Though which do I need, shared secret or secret identity?

**Comment by bukson** [comment]
Again from documentation:

If you have steamid, shared_secret and identity_secret you can place it in file Steamguard.txt instead of fetching SteamGuard file from device.

{ "steamid": "YOUR_STEAM_ID_64", "shared_secret": "YOUR_SHARED_SECRET", "identity_secret": "YOUR_IDENTITY_SECRET" }

**Comment by Zwork101** [comment]
Sorry, I thought that file would be in the program already, I didn't relize I had to make it. 🥇

**Pull request merged**
