### PR TITLE
Add catch for steam messing up

### PR DESCRIPTION
**Pull request by Zwork101**
Added a KeyError catch in case steam doesn't supply the correct json values. Will repeat function until it's obtained the correct value.

### CODE REVIEW

**Comment by Zwork101** [comment]
Also, @bukson, can you contact me, I have a question for you (I've tried to talk to you earlier, however you seemed busy)

**Comment by bukson** [comment]
Yeah i am busy because my supervisor of my master thesis want me to write paper on conference so i have a little time for other matters :) For this commit i don't like possible ifinite reccurence here, maybe add some counter and when counter = MAX_TRY (5 for example) than raise exception

**Comment by Zwork101** [comment]
Alright, messaging me when you have time would be greatly appreciated :D

**Comment by bukson** [comment]
Hmm ok it is no what i expected with repetition but is ok, today i will merge it and deploy new version when i get some time.

**Comment by bukson** [comment]
Resolved with https://github.com/bukson/steampy/commit/9425b8864df2715c90e10b03d9b886c176e16885
I didint like the variable inside class because its the internal part of this function so i resolved it with default parameter

**Pull request closed without merging**
