### PR TITLE
Community Fixes

### PR DESCRIPTION
**Pull request by maromalo**
Combines multiple fixes left in comments: 
- https://github.com/bukson/steampy/issues/382#issuecomment-2036162567 (Credits to @Marvin0729)
- https://github.com/bukson/steampy/issues/385#issuecomment-2039923688 (Credits to @lspeed-v)
- https://github.com/bukson/steampy/issues/343#issuecomment-1901125725 (Credits to @xidios)
- https://github.com/bukson/steampy/issues/354#issuecomment-1960536061 (Credits to @lexzach)

These have personally fixed my issues.
There are other snippets around however I wasn't sure if they would fit nicely with these ones or if they still work, these ones are the newest I could find. If there's another fix that currently works for you please leave a comment.

### CODE REVIEW

**Comment by xidios** [comment]
GJ

**Comment by bukson** [comment]
Sorry for long not looking at pull requests, I will try to merge it this week, can you give some motivation for the cookies changes?

**Comment by xidios** [comment]
> Sorry for long not looking at pull requests, I will try to merge it this week, can you give some motivation for the cookies changes?

image

**Comment by xidios** [comment]
> Sorry for long not looking at pull requests, I will try to merge it this week, can you give some motivation for the cookies changes?

image

**Comment by VlexWest** [comment]
> Sorry for long not looking at pull requests, I will try to merge it this week, can you give some motivation for the cookies changes?

Welcome back! 🚀🤗

65d4a38873c61

**Comment by bukson** [comment]
Fixed some code style and merged, this is my Christmas gift for you guys, now time for new version!

**Pull request closed without merging**
