### PR TITLE
Add check in setup.py

### PR DESCRIPTION
**Pull request by woctezuma**
Add the check which was removed by mistake in:
- #322

The check was removed due to https://docs.astral.sh/ruff/rules/outdated-version-block/, because the target version was higher than 3.8.

### CODE REVIEW

**Comment by bukson** [comment]
I think we should bump minimal python version to 3.10 anyway, so you can change that. The refurbishment pull request makes that possible and seamless right?

**Comment by woctezuma** [comment]
Yes, the refurbishment was performed with Python 3.12 in mind when running `ruff`.

**Comment by bukson** [comment]
So maybe can you set check for python 3.12 and just make it 3.12 project :) I think it is time

**Comment by woctezuma** [comment]
Alright. I have added minor fixes as well.

**Comment by woctezuma** [comment]
By the way, maybe, I am missing something, but I don't see where `store_cookie` is defined in:

https://github.com/bukson/steampy/blob/33a5cd91dddd6864f5297bfd37698d5da0e98e9d/steampy/login.py#L56-L69

**Comment by bukson** [comment]
Merged manually, thanks!

**Pull request closed without merging**
