### PR TITLE
Fix error when confirming sell listing

### PR DESCRIPTION
**Pull request by iamdlm**
I was getting a "ValueError: substring not found" exception.

### CODE REVIEW

**Comment by bukson** [comment]
Do you have any example that show that this change works?

**Comment by iamdlm** [comment]
`text` was returning `''`, no problems with `string`. I can attach some print screens of the error and properties.

**Comment by bukson** [comment]
Can you show some confirmation_details_page as the argument of the function requiers?

**Comment by bukson** [comment]
You can print the argumetn of that function and post it here

**Comment by iamdlm** [comment]
`<script type="text/javascript">\r\n\tvar g_rgAppContextData = {"730":{"appid":730,"name":"Counter-Strike: Global Offensive","icon":"https:\\/\\/steamcdn-a.akamaihd.net\\/steamcommunity\\/public\\/images\\/apps\\/730\\/69f7ebe2735c366c65c0b33dae00e12dc40edbe4.jpg","link":"https:\\/\\/steamcommunity.com\\/app\\/730"}};\r\n</script>\r\n<div>\r\n\t<div style="padding: 10px; color: #7A7A7A; text-align: center">To post this listing, confirm the item and price and select "Create Listing" below.</div>\r\n\t<div class="mobileconf_listing_prices">\r\n\t\t<div style="font-size: 20px;">\r\n\t\t\tYou want to sell...\t\t</div>\r\n\t\t<div style="color: #66C0F4; margin-top: 6px;">\r\n\t\t\t<div style="display: inline-block; min-width: 37.5%;">\r\n\t\t\t\tYou receive<br>\r\n\t\t\t\t2,82€\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t<div style="display: inline-block">\r\n\t\t\t\tBuyer pays<br>\r\n\t\t\t\t3,24€\t\t\t\t\t\t\t</div>\r\n\t\t</div>\r\n\t\t<div style="margin-top: 6px; color: #CACACA">\r\n\t\t\t<div>\r\n\t\t\t\t7 for sale starting at 3,11€\t\t\t</div>\r\n\t\t\t<div>\r\n\t\t\t\tVolume: 18 sold in the last 24 hours\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</div>\r\n<script>\r\n\tg_bIsTrading = true;\r\n</script>\r\n<div style="text-align: center; margin: 0 10px">\r\n\t<div class="inventory_iteminfo" id="confiteminfo" style="display: none;">\r\n\t<div class="item_desc_content" id="confiteminfo_content">\r\n\t\t<div class="item_desc_icon">\r\n\t\t\t<div class="item_desc_icon_center">\r\n\t\t\t\t\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t\t<div class="item_desc_description">\r\n\t\t\t<h1 class="hover_item_name" id="confiteminfo_item_name"></h1>\r\n\t\t\t\t\t\t\t<div class="fraud_warning" id="confiteminfo_fraud_warnings"></div>\r\n\t\t\t\t\t\t<div class="item_desc_game_info" id="confiteminfo_game_info">\r\n\t\t\t\t<div class="item_desc_game_icon">\r\n\t\t\t\t\t\r\n\t\t\t\t</div>\r\n\t\t\t\t<div id="confiteminfo_game_name" class="ellipsis"></div>\r\n\t\t\t\t<div id="confiteminfo_item_type" class=""></div>\r\n\t\t\t</div>\r\n\t\t\t<div class="item_desc_descriptors" id="confiteminfo_item_descriptors">\r\n\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t\t<div class="item_desc_descriptors" id="confiteminfo_item_owner_descriptors">\r\n\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t</div>\r\n\t\t</div>\r\n\t<script type="text/javascript">\r\n\t\tif ( document.readyState === "complete" ) {\r\n\t\t\tBuildHover( \'confiteminfo\', {"currency":0,"appid":730,"contextid":"2","id":"20081886584","classid":"4120372549","instanceid":"519977179","amount":"1","status":0,"original_amount":"1","background_color":"","icon_url":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoor-mcjhoyszJfz5L6dKiq5SCm_LnDKvUl2hZ1810i__Yu96t0VDk_0A_Z2D6LNPHIFU6Mg3W_ljtxLvoh5Hq75Scy3Zh7CAnt3nD30vgE8Lw6Bo","icon_url_large":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoor-mcjhoyszJfz5L6dKiq5SCm_LnDKvUl2hZ1810i__YyoD0mlOx5UFkaj3zIIXGdg83aQ2CqAK6krvpgZ_vucjOy3U16Sl353vfyRWy0x5SLrs4D8WkPg8","descriptions":[{"type":"html","value":"Exterior: Battle-Scarred"},{"type":"html","value":" "},{"type":"html","value":"An ideal pistol for the Terrorist on the move, the Tec-9 is lethal in close quarters and features a high magazine capacity. A pale green and beige pattern of ancient tiles has been applied.\\n\\n<i>\\"Hope remains, even for those began their journey down the wrong path\\"<\\/i>"},{"type":"html","value":" "},{"type":"html","value":"The Ancient Collection","color":"9da1a9"},{"type":"html","value":" "}],"tradable":0,"actions":[{"link":"steam:\\/\\/rungame\\/730\\/76561202255233023\\/+csgo_econ_action_preview%20S%owner_steamid%A%assetid%D9827536548066178838","name":"Inspect in Game..."}],"owner_descriptions":[{"type":"html","value":" "},{"type":"html","value":"Tradable After Dec 15, 2020 (8:00:00) GMT","color":"ff4040"}],"name":"Tec-9 | Blast From the Past","name_color":"D2D2D2","type":"Mil-Spec Grade Pistol","market_name":"Tec-9 | Blast From the Past (Battle-Scarred)","market_hash_name":"Tec-9 | Blast From the Past (Battle-Scarred)","market_actions":[{"link":"steam:\\/\\/rungame\\/730\\/76561202255233023\\/+csgo_econ_action_preview%20M%listingid%A%assetid%D9827536548066178838","name":"Inspect in Game..."}],"commodity":0,"market_tradable_restriction":7,"marketable":1}, UserYou );\r\n\t\t\t$( \'confiteminfo\' ).show();\r\n\t\t} else {\r\n\t\t\tEvent.observe( window, \'load\', function () {\r\n\t\t\t\tBuildHover( \'confiteminfo\', {"currency":0,"appid":730,"contextid":"2","id":"20081886584","classid":"4120372549","instanceid":"519977179","amount":"1","status":0,"original_amount":"1","background_color":"","icon_url":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoor-mcjhoyszJfz5L6dKiq5SCm_LnDKvUl2hZ1810i__Yu96t0VDk_0A_Z2D6LNPHIFU6Mg3W_ljtxLvoh5Hq75Scy3Zh7CAnt3nD30vgE8Lw6Bo","icon_url_large":"-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpoor-mcjhoyszJfz5L6dKiq5SCm_LnDKvUl2hZ1810i__YyoD0mlOx5UFkaj3zIIXGdg83aQ2CqAK6krvpgZ_vucjOy3U16Sl353vfyRWy0x5SLrs4D8WkPg8","descriptions":[{"type":"html","value":"Exterior: Battle-Scarred"},{"type":"html","value":" "},{"type":"html","value":"An ideal pistol for the Terrorist on the move, the Tec-9 is lethal in close quarters and features a high magazine capacity. A pale green and beige pattern of ancient tiles has been applied.\\n\\n<i>\\"Hope remains, even for those began their journey down the wrong path\\"<\\/i>"},{"type":"html","value":" "},{"type":"html","value":"The Ancient Collection","color":"9da1a9"},{"type":"html","value":" "}],"tradable":0,"actions":[{"link":"steam:\\/\\/rungame\\/730\\/76561202255233023\\/+csgo_econ_action_preview%20S%owner_steamid%A%assetid%D9827536548066178838","name":"Inspect in Game..."}],"owner_descriptions":[{"type":"html","value":" "},{"type":"html","value":"Tradable After Dec 15, 2020 (8:00:00) GMT","color":"ff4040"}],"name":"Tec-9 | Blast From the Past","name_color":"D2D2D2","type":"Mil-Spec Grade Pistol","market_name":"Tec-9 | Blast From the Past (Battle-Scarred)","market_hash_name":"Tec-9 | Blast From the Past (Battle-Scarred)","market_actions":[{"link":"steam:\\/\\/rungame\\/730\\/76561202255233023\\/+csgo_econ_action_preview%20M%listingid%A%assetid%D9827536548066178838","name":"Inspect in Game..."}],"commodity":0,"market_tradable_restriction":7,"marketable":1}, UserYou );\r\n\t\t\t\t$( \'confiteminfo\' ).show();\r\n\t\t\t} );\r\n\t\t}\r\n\t</script>\r\n</div>\r\n<div style="clear: both; padding: 10px; color: #7A7A7A; text-align: center">\r\n\t<span style="color: white; font-weight: bold;">Didn\'t create this listing?</span>\r\n\tThen your account or computer may have been compromised. If you don\'t recognize this activity, please cancel the listing immediately and change your Steam password.</div>\r\n<div style="width: 1px; height: 66px"></div>`

**Comment by bukson** [comment]
Ok I will check if it works tomorrow and commit if your solution works:)

**Comment by iamdlm** [comment]
Did you had the chance to test this?

**Comment by bukson** [comment]
Sorry I was busy, I will try to merge this in the following days

**Comment by iamdlm** [comment]
Updates on this?

**Comment by bukson** [comment]
Sure now I finally have time for merging this, I don't like changing the price to cents, its a hard core break of backwards comatibilty, I will try to find some fix for this

**Comment by bukson** [comment]
Ok it has nothing to do with this commit, I am merging it

**Comment by iamdlm** [comment]
Great! The price change to cents it's only in docs, you're already using cents in code and it's what Steam uses too.

**Comment by bukson** [comment]
Changes on master, I will deploy it  soon

**Pull request closed without merging**
