### PR TITLE
Add price history method

### PR DESCRIPTION
**Pull request by lrleo**
Making a pricing algorithm using only median lowest price sometimes does not work and leads to poor performance. By adding a price history method, it is now possible to calculate trends, volatility and confidence intervals.

The data returned by the method is a list of the points used by the graph, where each point is represented by [date, price, volume].

### CODE REVIEW

**Comment by bukson** [comment]
Hi.

A little bit late, but i am testing this method with 2 items: AWP | Asiimov (Field-Tested) and M4A1-S | Cyrex (Factory New) and it always returns empty list.

My test code:

**Comment by bukson** [comment]
Probably it is because it returns 400 bad request.

**Comment by lrleo** [comment]
Hi,

Thanks for giving an example. Upon closer inspection, I noticed that the method only works when logged in. Could you test it after a client login?

This doesn't make too much sense as the price graph is always available. I will take a look why it happens and correct it probably this week.

**Comment by bukson** [comment]
Yep it is that, I'v added login_required and it works.

I will add documentation entry, test and merge it tomorrow, thanks!

**Comment by bukson** [comment]
Ok I already merged it on master, and push it on pip with version 0.55, thanks!

**Pull request closed without merging**
