### PR TITLE
Add relogin method?

### PR DESCRIPTION
**Pull request by Zwork101**
I personally find this helpful. I'm not sure why password wasn't being saved to the Client object in the first place, also.

### CODE REVIEW

**Comment by ThreadShakur** [comment]
Is this method work? I'm use this lib in my site and have big experiance. Try to login anf relogin in one script, login at second attempt not work

**Comment by Zwork101** [comment]
Good point, I havn't tested it. Does it raise an error when you try to login the second time?

**Comment by ThreadShakur** [comment]
Steam just return response with error, i forgot message in this error

**Comment by Zwork101** [comment]
It would be helpful to know what it was. I personally have never seen it. Although I don't re-login much

**Comment by Ermans** [comment]
Wouldn't be better to pass the parameters to the login method?

**Comment by bukson** [comment]
So this method is basically the login method, but without parameters. 

I don't like it.

**Comment by ThreadShakur** [comment]
Also it not works, if you will fix problem with error in relogin, it will be helpful

**Comment by ThreadShakur** [comment]
I made some tests and relogin works, if you do it once per 1-2 minutes

**Comment by maxtwen** [comment]
Make a release with this change, pls

**Comment by bukson** [comment]
I think you can simulate it with normal login, closing issue.

Sorry for long time now see but i have many tasks on me. But i have got my master thesis in computer science :)

**Pull request closed without merging**
