### PR TITLE
added test for test_texts_between

### PR DESCRIPTION
**Pull request by crey4fun**
texts_between is a generator to iterate through all texts between two strings.
This test shows an example of a HTML list with 2 elements.

### CODE REVIEW

**Comment by bukson** [comment]
Oh ok i see you change 1 file on github per pull request.

**Comment by crey4fun** [comment]
Yeah cause I don't know how to change multiple files at once. Sorry

**Comment by bukson** [comment]
I dont see why, but i am doing allmost everything with console ok i can handle that

**Comment by bukson** [comment]
Merged

**Pull request closed without merging**
